site:
  title: PlatformKit Docs
  start_page: pk-modules::index.adoc

content:
  sources:
    - url: ../pk-modules
      start_path: .generated/antora

ui:
  bundle:
    url: ./antora-ui

output:
  dir: ./apps/antora/dist

runtime:
  fetch: false
